### Default ###
spring:
  profiles:
    active: local
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    property:
      prefix: ENC(
      suffix: )
    algorithm: PBEWithMD5AndDES
custom:
  iamport:
    api-key: ENC(3kgXokKn0qTHPo1G2BjET160prUBcKuaqPgY6Qq8PTw==)
    secret: ENC(Ee+LkQqPvpJyYyppl12TgAAd1on8a0VWyz2nEIDhq/2vaN+hlT8NFPaUhy8UTs+w7daRAcj19dSJCxqVyEdwqB+MjRqadMeglzQJK0aDRPZISsO1smXSr6zmSxoaLHGu)
  jwt:
    secret: ENC(JvO/H7QvecwZnzmStZ9mSMwA82V3PxSSbwrw6FQdsl6Z9zTN9/DovZ2P3eE5azmhJDPlgZcRYWnIhBeZwBOa1sf7E2xX7ZG8lSSIg1EzEcxFjOR/4zMbtA==)
  refund:
    application:
      code: 990
logging:
  config: classpath:log4j2.yml

---

### Local Environment ###
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: create
custom:
  refund:
    server: ENC(vIOoRRzJSa0iqX39B4ogkiYcB9p++ieiU4J6sGZXUAXXWm4/TDvC6A==)
server:
  port: 80

---

### Deploy ###
spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    url: ENC(Lh046F4eVLP478NbdyLZN+kPl5m4AEvLtpUCyHXlSzuC3oatpY/BWUMPtGccxyI+JBKg/ZVfhw9ot9avS5w4Li6QqYxwzACyFmU/QhjUagmYqHuWbWWxIACKWbx1zrwwlIlwBxCUTLfwwy/CqusDJS3jqZqoUDR1f521q0Wu8L5/h4BK1Kp/Yg==)
    username: ENC(0Jwk1Hd6bYJexLqbNVfZAA==)
    password: ENC(SmfyeK1HXJGN9vG15TmvGz8Tara1kwXW)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: none
custom:
  refund:
    server: ENC(vIOoRRzJSa0iqX39B4ogkiYcB9p++ieiU4J6sGZXUAXXWm4/TDvC6A==)
server:
  port: 20001
